/* Ghost interviewer dashboard.
   No framework and no build step - the whole point is that a judge can run
   `python3 -m ghost.server` and have a working surface. */

(function () {
  "use strict";

  var state = { session: null, dispositions: {} };

  var $ = function (id) { return document.getElementById(id); };
  var el = function (tag, className, text) {
    var node = document.createElement(tag);
    if (className) { node.className = className; }
    if (text !== undefined && text !== null) { node.textContent = text; }
    return node;
  };

  function setStatus(message, isError) {
    var node = $("status");
    node.textContent = message || "";
    node.classList.toggle("is-error", Boolean(isError));
  }

  function setBusy(busy) {
    ["btn-prepare", "btn-review", "btn-sample"].forEach(function (id) {
      $(id).disabled = busy;
    });
  }

  function post(path, body) {
    return fetch(path, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body)
    }).then(readResponse);
  }

  function readResponse(response) {
    return response.json().catch(function () {
      throw new Error("server returned " + response.status);
    }).then(function (data) {
      if (!response.ok) { throw new Error(data.error || "server error"); }
      return data;
    });
  }

  /* ---------- navigation ---------- */
  function showView(name) {
    document.querySelectorAll(".view").forEach(function (view) {
      view.classList.toggle("is-active", view.id === "view-" + name);
    });
    document.querySelectorAll(".tab").forEach(function (tab) {
      tab.classList.toggle("is-active", tab.dataset.view === name);
    });
  }

  function enableTabs(names) {
    document.querySelectorAll(".tab").forEach(function (tab) {
      if (names.indexOf(tab.dataset.view) !== -1) { tab.disabled = false; }
    });
  }

  /* ---------- rendering: guide ---------- */
  function renderGuide(session) {
    $("guide-title").textContent = "Interview guide — " + session.candidate.name;
    $("guide-sub").textContent =
      session.role.title + " · " + session.questions.length + " questions · generated by " + session.engine;

    var chips = $("guide-competencies");
    chips.innerHTML = "";
    (session.role.competencies || []).forEach(function (competency) {
      chips.appendChild(el("span", "badge badge-neutral", competency));
    });

    var list = $("guide-list");
    list.innerHTML = "";
    if (!session.questions.length) {
      list.appendChild(el("div", "empty", "No questions generated."));
      return;
    }

    session.questions.forEach(function (question, index) {
      var card = el("div", "card");
      var head = el("div", "card-head");
      head.appendChild(el("div", "card-title", (index + 1) + ". " + question.text));
      var meta = el("div", "card-meta");
      meta.appendChild(el("span", "badge badge-accent", question.difficulty));
      meta.appendChild(el("span", "badge badge-neutral", question.competency));
      head.appendChild(meta);
      card.appendChild(head);

      if (question.grounded_in) {
        card.appendChild(el("div", "grounding", "Grounded in: " + question.grounded_in));
      }
      if (question.looking_for) {
        var dl = el("dl", "detail-row");
        dl.appendChild(el("dt", null, "Listen for"));
        dl.appendChild(el("dd", null, question.looking_for));
        card.appendChild(dl);
      }
      if (question.follow_ups && question.follow_ups.length) {
        var ul = el("ul", "followups");
        question.follow_ups.forEach(function (followUp) {
          ul.appendChild(el("li", null, followUp));
        });
        card.appendChild(ul);
      }
      list.appendChild(card);
    });
  }

  /* ---------- rendering: transcript ---------- */
  function renderTranscript(session) {
    var signals = (session.report && session.report.signals) || [];
    var byTurn = {};
    signals.forEach(function (signal) {
      (byTurn[signal.turn_index] = byTurn[signal.turn_index] || []).push(signal);
    });

    $("transcript-sub").textContent =
      session.transcript.length + " turns · " + Object.keys(byTurn).length + " flagged";

    var flaggedOnly = $("toggle-flagged").checked;
    var list = $("transcript-list");
    list.innerHTML = "";

    session.transcript.forEach(function (turn, index) {
      var turnSignals = byTurn[index] || [];
      if (flaggedOnly && !turnSignals.length) { return; }

      var row = el("div", "turn role-" + turn.role + (turnSignals.length ? " is-flagged" : ""));
      var time = el("div", "turn-time");
      time.appendChild(el("div", null, turn.timestamp));
      if (turn.role === "candidate" && turn.latency_s) {
        time.appendChild(el("div", null, "+" + turn.latency_s.toFixed(1) + "s"));
      }
      row.appendChild(time);

      var body = el("div");
      body.appendChild(el("div", "turn-speaker", turn.speaker));
      body.appendChild(el("div", "turn-text", turn.text));
      if (turnSignals.length) {
        var flags = el("div", "turn-flags");
        turnSignals.forEach(function (signal) {
          flags.appendChild(el("span", "badge badge-" + signal.severity, signal.kind.replace(/_/g, " ")));
        });
        body.appendChild(flags);
      }
      row.appendChild(body);
      list.appendChild(row);
    });

    if (!list.children.length) {
      list.appendChild(el("div", "empty", "No turns to show."));
    }
  }

  /* ---------- rendering: report ---------- */
  function renderReport(session) {
    var report = session.report;
    $("report-title").textContent =
      "Evidence report — " + report.candidate + " · " + report.role;
    $("report-headline").textContent = report.headline;
    $("report-disclaimer").textContent = report.disclaimer;

    var counts = report.signal_counts || {};
    var stats = $("report-stats");
    stats.innerHTML = "";
    [
      { label: "Worth re-watching", value: counts.high || 0 },
      { label: "Worth a second read", value: counts.medium || 0 },
      { label: "Minor notes", value: counts.low || 0 },
      { label: "Questions answered", value: report.packets.filter(function (p) { return p.candidate_answer; }).length },
      { label: "Interview length", value: Math.round(report.duration_s / 60) + " min" }
    ].forEach(function (item) {
      var stat = el("div", "stat");
      stat.appendChild(el("div", "stat-value", String(item.value)));
      stat.appendChild(el("div", "stat-label", item.label));
      stats.appendChild(stat);
    });

    renderSignals(report.signals);
    renderCoverage(report.coverage);
    renderPackets(report.packets);
    renderBaseline(report.baseline);
  }

  function renderSignals(signals) {
    var list = $("signal-list");
    list.innerHTML = "";
    if (!signals.length) {
      list.appendChild(el("div", "empty",
        "Nothing was flagged for review. The transcript and evidence packets are still recorded below."));
      return;
    }
    signals.forEach(function (signal) {
      var card = el("div", "card card-signal sev-" + signal.severity);
      var head = el("div", "card-head");
      head.appendChild(el("div", "card-title", signal.timestamp + " — " + signal.summary));
      var meta = el("div", "card-meta");
      meta.appendChild(el("span", "badge badge-" + signal.severity, signal.severity));
      meta.appendChild(el("span", "badge badge-neutral", signal.kind.replace(/_/g, " ")));
      meta.appendChild(el("span", "badge badge-neutral",
        "confidence " + Math.round(signal.confidence * 100) + "%"));
      head.appendChild(meta);
      card.appendChild(head);

      card.appendChild(el("p", "muted", signal.rationale));
      if (signal.quote) { card.appendChild(el("div", "quote", "“" + signal.quote + "”")); }
      if (signal.suggested_follow_up) {
        var dl = el("dl", "detail-row");
        dl.appendChild(el("dt", null, "Try asking"));
        dl.appendChild(el("dd", null, signal.suggested_follow_up));
        card.appendChild(dl);
      }
      list.appendChild(card);
    });
  }

  function renderCoverage(coverage) {
    var list = $("coverage-list");
    list.innerHTML = "";
    Object.keys(coverage || {}).forEach(function (competency) {
      var row = el("div", "coverage-row");
      row.appendChild(el("span", null, competency));
      row.appendChild(el("span", null, coverage[competency]));
      list.appendChild(row);
    });
    if (!list.children.length) {
      list.appendChild(el("div", "empty", "No competency model derived."));
    }
  }

  function renderBaseline(baseline) {
    var list = $("baseline-list");
    list.innerHTML = "";
    if (!baseline || !Object.keys(baseline).length) {
      list.appendChild(el("div", "empty", "No baseline available."));
      return;
    }
    var labels = {
      turns: "Candidate turns",
      median_latency_s: "Median response gap (s)",
      median_words: "Median answer length (words)",
      median_sentence_length: "Median sentence length (words)",
      median_filler_per_100w: "Fillers per 100 words",
      baseline_reliable: "Baseline reliable"
    };
    Object.keys(labels).forEach(function (key) {
      if (!(key in baseline)) { return; }
      var value = baseline[key];
      if (typeof value === "boolean") { value = value ? "yes" : "no — too few turns"; }
      var row = el("div", "coverage-row");
      row.appendChild(el("span", null, labels[key]));
      row.appendChild(el("span", null, String(value)));
      list.appendChild(row);
    });
  }

  function renderPackets(packets) {
    var list = $("packet-list");
    list.innerHTML = "";
    packets.forEach(function (packet) {
      var card = el("div", "card");
      var head = el("div", "card-head");
      head.appendChild(el("div", "card-title", packet.question));
      var meta = el("div", "card-meta");
      meta.appendChild(el("span", "badge badge-neutral", packet.competency));
      if (!packet.candidate_answer) {
        meta.appendChild(el("span", "badge badge-neutral", "not asked"));
      }
      head.appendChild(meta);
      card.appendChild(head);

      if (!packet.candidate_answer) {
        card.appendChild(el("p", "muted", "This question was not asked in the interview."));
        list.appendChild(card);
        return;
      }

      card.appendChild(el("div", "quote", "[" + packet.timestamp + "] " + packet.transcript_quote));

      if (packet.follow_up_question) {
        var followDl = el("dl", "detail-row");
        followDl.appendChild(el("dt", null, "Follow-up"));
        followDl.appendChild(el("dd", null, packet.follow_up_question));
        card.appendChild(followDl);
      }
      if (packet.follow_up_answer) {
        card.appendChild(el("div", "quote", packet.follow_up_answer));
      }
      if (packet.unverified_claim) {
        var claimDl = el("dl", "detail-row");
        claimDl.appendChild(el("dt", null, "Not evidenced"));
        claimDl.appendChild(el("dd", null, packet.unverified_claim));
        card.appendChild(claimDl);
      }
      if (packet.signals && packet.signals.length) {
        var flags = el("div", "turn-flags");
        packet.signals.forEach(function (signal) {
          flags.appendChild(el("span", "badge badge-" + signal.severity,
            signal.kind.replace(/_/g, " ") + " · " + signal.timestamp));
        });
        card.appendChild(flags);
      }

      card.appendChild(buildDisposition(packet));
      list.appendChild(card);
    });
  }

  function buildDisposition(packet) {
    var wrap = el("div", "disposition");
    wrap.appendChild(el("span", "muted", "Your call:"));

    var select = document.createElement("select");
    ["— not recorded —", "evidence supports the claim", "partially evidenced",
     "not evidenced", "needs another interview"].forEach(function (option, index) {
      var node = el("option", null, option);
      node.value = index === 0 ? "" : option;
      select.appendChild(node);
    });

    var rationale = document.createElement("input");
    rationale.type = "text";
    rationale.placeholder = "Your rationale (recorded with the packet)";

    var saved = state.dispositions[packet.question_id];
    if (saved) {
      select.value = saved.disposition || "";
      rationale.value = saved.rationale || "";
    }

    function save() {
      state.dispositions[packet.question_id] = {
        disposition: select.value,
        rationale: rationale.value
      };
    }
    select.addEventListener("change", save);
    rationale.addEventListener("input", save);

    wrap.appendChild(select);
    wrap.appendChild(rationale);
    return wrap;
  }

  /* ---------- session handling ---------- */
  function applySession(session) {
    state.session = session;
    renderGuide(session);
    enableTabs(["guide"]);

    if (session.transcript && session.transcript.length) {
      renderTranscript(session);
      enableTabs(["transcript"]);
    }
    if (session.report) {
      renderReport(session);
      enableTabs(["report"]);
      showView("report");
    } else {
      showView("guide");
    }
  }

  function currentInputs() {
    return {
      portfolio: $("in-portfolio").value,
      job_description: $("in-jd").value,
      transcript: $("in-transcript").value,
      question_count: Number($("in-count").value) || 8
    };
  }

  /* ---------- wiring ---------- */
  document.querySelectorAll(".tab").forEach(function (tab) {
    tab.addEventListener("click", function () {
      if (!tab.disabled) { showView(tab.dataset.view); }
    });
  });

  $("toggle-flagged").addEventListener("change", function () {
    if (state.session) { renderTranscript(state.session); }
  });

  $("btn-prepare").addEventListener("click", function () {
    var inputs = currentInputs();
    if (!inputs.portfolio.trim() || !inputs.job_description.trim()) {
      setStatus("Paste a portfolio and a job description first.", true);
      return;
    }
    setBusy(true);
    setStatus("Generating interview guide…");
    post("/api/prepare", inputs).then(function (session) {
      applySession(session);
      setStatus("Guide ready — " + session.questions.length + " questions.");
    }).catch(function (error) {
      setStatus(error.message, true);
    }).then(function () { setBusy(false); });
  });

  $("btn-review").addEventListener("click", function () {
    var inputs = currentInputs();
    if (!inputs.transcript.trim()) {
      setStatus("Paste a Teams transcript to generate a report.", true);
      return;
    }
    setBusy(true);
    setStatus("Reviewing transcript…");
    post("/api/review", inputs).then(function (session) {
      applySession(session);
      setStatus("Report ready.");
    }).catch(function (error) {
      setStatus(error.message, true);
    }).then(function () { setBusy(false); });
  });

  $("btn-sample").addEventListener("click", function () {
    setBusy(true);
    setStatus("Loading the sample interview…");
    fetch("/api/sample").then(readResponse).then(function (session) {
      $("in-portfolio").value = session.inputs.portfolio;
      $("in-jd").value = session.inputs.job_description;
      $("in-transcript").value = session.inputs.transcript;
      state.dispositions = {};
      applySession(session);
      setStatus("Sample loaded.");
    }).catch(function (error) {
      setStatus(error.message, true);
    }).then(function () { setBusy(false); });
  });

  $("btn-export").addEventListener("click", function () {
    if (!state.session || !state.session.report_markdown) { return; }
    var markdown = state.session.report_markdown + dispositionAppendix();
    navigator.clipboard.writeText(markdown).then(function () {
      setStatus("Report copied to the clipboard.");
    }).catch(function () {
      setStatus("Could not access the clipboard.", true);
    });
  });

  function dispositionAppendix() {
    var entries = Object.keys(state.dispositions).filter(function (key) {
      var entry = state.dispositions[key];
      return entry.disposition || entry.rationale;
    });
    if (!entries.length) { return ""; }
    var lines = ["", "## Interviewer dispositions", ""];
    entries.forEach(function (key) {
      var entry = state.dispositions[key];
      lines.push("- **" + key + "** — " + (entry.disposition || "no disposition") +
        (entry.rationale ? ": " + entry.rationale : ""));
    });
    return lines.join("\n");
  }

  /* ---------- boot ---------- */
  fetch("/api/health").then(readResponse).then(function (health) {
    var badge = $("engine-badge");
    badge.textContent = "engine: " + health.engine;
    badge.className = "badge " + (health.azure_configured ? "badge-accent" : "badge-neutral");
    badge.title = health.azure_configured
      ? "Questions and review are generated by Azure OpenAI."
      : "Running the offline engine. Set AZURE_OPENAI_ENDPOINT, _API_KEY and _DEPLOYMENT to use Azure OpenAI.";
  }).catch(function () {
    $("engine-badge").textContent = "engine: unavailable";
  });
}());
