"""Command line entry point.

    python3 -m ghost.cli demo
    python3 -m ghost.cli prepare --portfolio cv.md --job jd.md
    python3 -m ghost.cli review  --portfolio cv.md --job jd.md --transcript teams.vtt
"""

import argparse
import json
import os
import sys
from typing import Optional

from .config import engine_name
from .pipeline import run
from .report import to_markdown

SAMPLE_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data", "samples"
)


def _read(path: str) -> str:
    with open(path, "r", encoding="utf-8") as handle:
        return handle.read()


def _emit(session, as_json: bool, output: Optional[str]) -> None:
    if as_json:
        text = json.dumps(session.to_dict(), indent=2)
    elif session.report:
        text = to_markdown(session.report, session.transcript)
    else:
        text = _guide_text(session)

    if output:
        with open(output, "w", encoding="utf-8") as handle:
            handle.write(text)
        print("wrote {}".format(output))
    else:
        print(text)


def _guide_text(session) -> str:
    lines = [
        "# Interview guide - {}".format(session.profile.name),
        "",
        "**Role:** {}".format(session.spec.title),
        "**Competencies:** {}".format(", ".join(session.spec.competencies)),
        "**Generated by:** {}".format(engine_name()),
        "",
    ]
    for index, question in enumerate(session.questions, start=1):
        lines += [
            "## {}. [{}] {}".format(index, question.difficulty, question.competency),
            "",
            question.text,
            "",
        ]
        if question.grounded_in:
            lines += ["_Grounded in: {}_".format(question.grounded_in), ""]
        if question.looking_for:
            lines += ["**Listen for:** {}".format(question.looking_for), ""]
        for follow_up in question.follow_ups:
            lines.append("- {}".format(follow_up))
        lines.append("")
    return "\n".join(lines)


def _run_and_emit(args, transcript_path: Optional[str]) -> int:
    try:
        transcript_text = _read(transcript_path) if transcript_path else None
        session = run(
            _read(args.portfolio),
            _read(args.job),
            transcript_text=transcript_text,
            question_count=args.count,
            interview_date=getattr(args, "date", None),
        )
    except OSError as exc:
        print("error: {}".format(exc), file=sys.stderr)
        return 1
    _emit(session, args.json, args.output)
    return 0


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(prog="ghost", description="Interview evidence copilot")
    subparsers = parser.add_subparsers(dest="command", required=True)

    def add_common(sub):
        sub.add_argument("--count", type=int, default=8, help="number of questions (default 8)")
        sub.add_argument("--json", action="store_true", help="emit the full session as JSON")
        sub.add_argument("--output", "-o", help="write to a file instead of stdout")

    prepare = subparsers.add_parser("prepare", help="generate an interview guide")
    prepare.add_argument("--portfolio", required=True)
    prepare.add_argument("--job", required=True)
    add_common(prepare)

    review = subparsers.add_parser("review", help="generate an evidence report")
    review.add_argument("--portfolio", required=True)
    review.add_argument("--job", required=True)
    review.add_argument("--transcript", required=True, help=".vtt from Teams, or Ghost JSON")
    review.add_argument("--date", help="interview date (YYYY-MM-DD)")
    add_common(review)

    demo = subparsers.add_parser("demo", help="run the bundled sample interview end to end")
    add_common(demo)

    serve = subparsers.add_parser("serve", help="run the interviewer dashboard")
    serve.add_argument("--host", default="127.0.0.1")
    serve.add_argument("--port", type=int, default=8000)

    args = parser.parse_args(argv)

    if args.command == "serve":
        from .server import serve as run_server

        run_server(args.host, args.port)
        return 0

    if args.command == "demo":
        args.portfolio = os.path.join(SAMPLE_DIR, "portfolio_priya_raman.md")
        args.job = os.path.join(SAMPLE_DIR, "job_description_senior_backend.md")
        args.date = "2026-07-29"
        return _run_and_emit(args, os.path.join(SAMPLE_DIR, "interview_priya_raman.vtt"))

    if args.command == "prepare":
        return _run_and_emit(args, None)

    return _run_and_emit(args, args.transcript)


if __name__ == "__main__":
    sys.exit(main())
